# Created using wingetcreate 0.4.4.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: notepad++.Notepad++new
PackageVersion: 8.1.9.2
PackageLocale: en-US
Publisher: DonHo
PackageName: Notepad++
License: MIT License
ShortDescription: 'Notepad ++ '
ManifestType: defaultLocale
ManifestVersion: 1.0.0

