# Created using wingetcreate 0.4.4.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: notepad++.Notepad++new
PackageVersion: 8.1.9.2
Installers:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://notepad-plus-plus.org/repository/7.x/7.0/npp.7.Installer.exe
  InstallerSha256: 0155C4AB117D63BA5142FC1090DEBC07DC7953264F7202EF8D25014E2CF8668D
ManifestType: installer
ManifestVersion: 1.0.0

